Feature/crocus noah3.9
NASA-LIS/LISF pull request #1026
Opened 2022-03-23 23:02 UTC by LIS-navari

### Description
We have already developed an infrastructure to couple the sub LSM with different LSMs. As a pilot study, we coupled Crocus and Noah-MP401. Here we add support for coupling Crocus and Noah39 LSM.  

Resolves #1025 

Replace this text with a concise description of *what* was changed and *why*.

### Testcase
# LDT 
/discover/nobackup/mnavari/my_projects/thp/submodel/noah39/procLSM
ldt.config.hymap

# LIS
/discover/nobackup/mnavari/my_projects/thp/submodel/noah39/nldas
lis.config
lis.job

2022-03-24 13:53 UTC, bmcandr commented
Hi @LIS-navari, can you please open permissions on the `output/` directory in your LIS testcase? Thanks!

2022-03-24 17:33 UTC, LIS-navari commented
Hi @bmcandr, You should have access to the output. Thanks

2022-03-28 20:48 UTC, bmcandr requested changes
Hi @LIS-navari, sorry for the delay. I have generated outputs with the latest Intel 2021 environment and see minor differences that I'm assuming are due to using different compiler versions (I see a LIS_19 in your testcase directory). I'm re-running the testcase with the Intel 19 environment to confirm.

On the code review front, things look good overall. See my one question ~above~ below about deleting some commented out lines. I'll handle the copyright notices.

Two questions:
* Is Crocus ready to be enabled in make/default.cfg? In #697 we decided that more work was needed so I just wanted to circle back on that.
* (if "yes" to the above question) Should Crocus be added to the documentation anywhere?

2022-03-28 20:48 UTC, bmcandr commented on lis/plugins/LIS_lsmrouting_pluginMod.F90
> +!   call registerlsmroutinggetsws(trim(LIS_noah39Id)//"+"//&
Can we delete this entry? Looks like it was moved down to lines 261.

2022-03-28 20:48 UTC, bmcandr commented on lis/surfacemodels/land/noah.3.9/routing/noah39_getrunoffs_hymap2.F90
> +!-------------------------END NOTICE -- DO NOT EDIT-----------------------
Update copyright notice

2022-03-28 20:48 UTC, bmcandr commented on lis/surfacemodels/land/noah.3.9/routing/noah39_getsws_hymap2.F90
> +!-----------------------BEGIN NOTICE -- DO NOT EDIT-----------------------
Update copyright notice

2022-07-18 13:49 UTC, emkemp commented
Hi Mahdi:

I dusted off this pull request and performed some testing.  I get identical results in the SURFACEMODEL history file, but I see some differences in the ROUTING file (both valid 00Z 2 Jan 2021).  I'm assuming these differences are due to my use of the Intel 2021 compiler.

I updated the copyright blocks in the new source code files you added to match what is in the master branch (LISf 7.4, copyright 2022).

The documentation still needs to be updated to reflect the CROCUS entries, as well as the subLSM model entry.  I need you to provide these updates before this pull request is "ready" to be merged.

2022-08-16 16:37 UTC, emkemp commented
*PING*

Hi @mahdi:

This pull request still needs additional documentation before we can accept your changes into master.

2022-08-16 21:46 UTC, LIS-navari commented
Hi @emkemp 

I have completed the documentation.

Thanks
Mahdi

2022-09-06 18:27 UTC, emkemp commented
Thanks @LIS-navari.

I need to coordinate with @jvgeiger on how to accept your test case before accepting the pull request.

2022-10-06 14:31 UTC, emkemp commented
Test cases copied to /discover/nobackup/projects/lis/PR_TESTCASES/1026.  I approve.

2022-10-06 14:31 UTC, merged