Feature/li siodist
NASA-LIS/LISF pull request #1042
Opened 2022-04-05 14:48 UTC by sujayvkumar

### Description

A new output format called 'distributed binary' was added. In this format, each processor writes outputs for the respective local domain to a binary file. At the output time steps, no synchronization is done to gather output variables across multiple processors. 

The quilting of the outputs across multiple processors is then done using LVT using a new run mode called "LIS post processing"

Resolves #1039 

### Testcase

A testcase can be found at : /discover/nobackup/projects/eis_freshwater/svkumar/Tests/LIS_test_distio

the lisrun directory contains the LIS example config. In this setup 16 processors should be used. 
the lvtrun directory then contains the configuration to quilt the files into a single file in netcdf format. 

The outputs will be generated in the same directory as that of the LIS output.

2022-04-05 19:17 UTC, bmcandr requested changes

2022-04-05 19:17 UTC, bmcandr commented on lis/core/LIS_fileIOMod.F90
> +! Copyright (c) 2015 United States Government as represented by the
Update copyright

2022-04-05 19:17 UTC, bmcandr commented on lis/core/LIS_fileIOMod.F90
> +      case ("distributed binary")
Add new output data format to docs

2022-04-05 19:17 UTC, bmcandr commented on lis/core/LIS_histDataMod.F90
> +         "vapor pressure deficit",rc)
Support for VPD output seems unrelated to distributed binary support. No need to change, just adding a comment so it is acknowledged in the PR.

2022-04-05 19:17 UTC, bmcandr commented on lis/core/LIS_historyMod.F90
> +    character*100 :: mname_temp,temp1,lsmoutfilep
Declare path/filename variables with length = `LIS_CONST_PATH_LEN`

2022-04-05 19:17 UTC, bmcandr commented on lvt/core/LVT_LISpostMod.F90
> +    call LVT_verify(rc,'Number of vertical levels in the LIS output: option not specified in the config file')
Add new config entries to docs

2022-04-05 19:17 UTC, bmcandr commented on lvt/core/LVT_LISpostMod.F90
> +!             write(LVT_logunit,*) '[INFO] Reading LIS output ',trim(fname(i))
Might be good to leave this log message in. Is there a reason for commenting it out?

2022-04-05 19:17 UTC, bmcandr commented on lvt/core/LVT_LISpostMod.F90
> +!         'nf90_put_att for title failed in LVT_LISpostMod')
Does adding these global attributes not work?

2022-04-05 19:17 UTC, bmcandr commented on lvt/core/LVT_fileIOMod.F90
> +              elseif(LVT_LIS_rc(source)%wopt.eq."2d ensemble gridspace") then
Add new output methodology (`2d ensemble gridspace`) and format (`distributed binary`) to docs

2022-04-05 19:17 UTC, bmcandr commented on lvt/core/LVT_histDataMod.F90
> +         default="pixel-by-pixel",&
Note new default value in docs

2022-04-05 19:17 UTC, bmcandr commented on lvt/core/LVT_readConfig.F90
> +       default = 0,&
Note new default values in docs

2022-04-05 19:31 UTC, bmcandr commented
Hi @sujayvkumar, I have completed my code review. I identified a few changes that I can take care of (mostly docs related). Two questions for you:

* In `lvt/core/LVT_LISpostMod.F90`:
    *  A log message is commented out. Is there a reason it is commented out? It might be worth keeping unless it spams the log.
    * The calls writing the global attributes `NUM_SOIL_LAYERS`, `SOIL_LAYER_THICKNESSES`, and `history` are disabled. Do they not work? (or are unnecessary?)

2022-04-05 19:53 UTC, sujayvkumar commented
@bmcandr : Thanks for the quick review. 
The log is commented out because it could lead to a ton of messages, particularly if the LIS run was done using a large number of processors. 

Yes - they are turned off because they are not present in the distributed binary outputs (and we don't want to include it there since this information doesn't change between outputs). I suppose we can make them configurable options in LVT and then embed them within the netcdf file.

2022-04-06 15:55 UTC, bmcandr commented on lvt/core/LVT_LISpostMod.F90
> +!         'nf90_put_att for title failed in LVT_LISpostMod')
See comment below. Will be fixed later.

2022-04-06 20:07 UTC, bmcandr approved these changes

2022-04-06 20:08 UTC, bmcandr commented
I am able to reproduce outputs with the Intel 21 compiler. Merging.

I will address the global attributes issue mentioned above in a subsequent PR.

2022-04-06 20:08 UTC, merged