New features in LDT for GVF CDF generation and SMAP_E_OPL retrievals
NASA-LIS/LISF pull request #1110
Opened 2022-06-07 16:32 UTC by yhkwon81

### Description

Codes for VIIRS and CDFS CDF generation and operational enhanced SMAP (SMAP_E_OPL) soil moisture retrievals have been added in LDT.

### Testcase
SMAP_E_OPL: /discover/nobackup/projects/usaf_lis/ykwon/SMAP_E_OPL/testcases/TEST_01_usecase
VIIRS CDF: /discover/nobackup/projects/usaf_lis/ykwon/SoilMoisture_DA/testcases/noahmp401/noahmp401_CONUS_10km_dynamic/DA_proc_VIIRS
CDFS CDF: /discover/nobackup/projects/usaf_lis/ykwon/SoilMoisture_DA/testcases/noahmp401/noahmp401_CONUS_10km_dynamic/DA_proc_CDFS

2022-06-10 20:31 UTC, yhkwon81 commented
Hi Brendan,

Thanks a lot for checking these.

Regarding the LDT codes, I fixed “LDT_DAobsDataMod.F90” and could compile LDT with “-2” mode.


  *   VIIRS CDF: the testcase directory contains a soft link to a VIIRS_CDF/ directory, but the target doesn't exist (/discover/nobackup/projects/usaf_lis/dmocko/gvf/VIIRS). Can you point me to another copy of these inputs?  • I updated the directory link. Could you check it again?
  *   SMAP_E_OPL: the ldt.config file points to /discover/nobackup/projects/usaf_lis/ykwon/SMAP_E_OPL/data/SMAP_L1B_historical, but I do not have read access on this directory.
• I changed the permission. Could you try to access it now?

Thanks,
Yonghwan


From: Brendan McAndrew ***@***.***>
Reply-To: NASA-LIS/LISF ***@***.***>
Date: Tuesday, June 7, 2022 at 9:26 PM
To: NASA-LIS/LISF ***@***.***>
Cc: "Kwon, Yonghwan (GSFC-617.0)[UNIVERSITY OF MARYLAND]" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [NASA-LIS/LISF] New features in LDT for GVF CDF generation and SMAP_E_OPL retrievals (PR #1110)


Hi again,

I am also unable to access input files needed for two of the testcases:

  *   VIIRS CDF: the testcase directory contains a soft link to a VIIRS_CDF/ directory, but the target doesn't exist (/discover/nobackup/projects/usaf_lis/dmocko/gvf/VIIRS). Can you point me to another copy of these inputs?
  *   SMAP_E_OPL: the ldt.config file points to /discover/nobackup/projects/usaf_lis/ykwon/SMAP_E_OPL/data/SMAP_L1B_historical, but I do not have read access on this directory.

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNASA-LIS%2FLISF%2Fpull%2F1110%23issuecomment-1149344271&data=05%7C01%7Cyonghwan.kwon%40nasa.gov%7Ce99e0a86b58c47c3902408da48eded19%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637902483981773544%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EIdUljeBcTLi4gFI8XBdxGzA2FcaeOa9NQEG5Sh7wKg%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMAPSH3REZIAGF6YAN32JZTVN7ZENANCNFSM5YDR5MYQ&data=05%7C01%7Cyonghwan.kwon%40nasa.gov%7Ce99e0a86b58c47c3902408da48eded19%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637902483981773544%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HFaeekav4JHR5Q7fd%2Fm4ACpvwXc6%2BR6HWmB76EI2T%2B0%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-06-10 20:48 UTC, bmcandr commented
Thanks @yhkwon81, I am able to access those files now.

2022-06-10 21:13 UTC, bmcandr commented
I'm now getting an error on the SMAP_E_OPL testcase:

```
forrtl: severe (408): fort: (2): Subscript #1 of the array ZERODISTFLAG has value 2555 which is greater than the upper bound of 1920

Image              PC                Routine            Line        Source
LDT.intel.21.defa  0000000000BF069F  Unknown               Unknown  Unknown
LDT.intel.21.defa  00000000008A1771  invdist_l1b2arfs_         121  invdist_l1b2arfs.F90
LDT.intel.21.defa  00000000006E6CAE  smapl1bresample_           63  SMAPL1BTOL1C_ARFS.F90
LDT.intel.21.defa  0000000000640125  ldt_smap_e_oplmod         272  LDT_smap_e_oplMod.F90
LDT.intel.21.defa  000000000063CC89  ldt_run_smap_e_op          25  LDT_run_smap_e_opl.F90
LDT.intel.21.defa  000000000063D198  Unknown               Unknown  Unknown
LDT.intel.21.defa  0000000000681059  MAIN__                     46  LDTmain.F90
LDT.intel.21.defa  0000000000414352  Unknown               Unknown  Unknown
libc-2.22.so       00002AAAB46F4725  __libc_start_main     Unknown  Unknown
LDT.intel.21.defa  0000000000414269  Unknown               Unknown  Unknown
```

I'm wondering if the array `zerodistflag` is being allocated with the dimensions swapped?

https://github.com/NASA-LIS/LISF/blob/59ea4a0f9d233f4b1a6bc22f1a0ec995c387ac2f/ldt/SMAP_E_OPL/invdist_l1b2arfs.F90#L39

2022-06-16 18:13 UTC, bmcandr requested changes
Hi @yhkwon81,

I am requesting a few more changes before we can merge this in. See the comments on the pull request in GitHub.

2022-06-16 18:13 UTC, bmcandr commented on ldt/SMAP_E_OPL/SMAPL1BTOL1C_ARFS.F90
> +   USE HDF5
Remove `USE HDF5`. Doesn't look like it is used in this subroutine.

2022-06-16 18:13 UTC, bmcandr commented on ldt/SMAP_E_OPL/TOOLSUBS.F90
> +    USE HDF5
Wrap in `#if (defined USE_HDF5)` preprocessor check.

2022-06-16 18:13 UTC, bmcandr commented on ldt/SMAP_E_OPL/TOOLSUBS.F90
> +        sm_mat = data_out(lon_ind(1):lon_ind(size(lon_ind)),lat_ind(1):lat_ind(size(lat_ind)))
Wrap in `#if (defined USE_HDF5)` preprocessor check.

2022-06-16 18:13 UTC, bmcandr commented on ldt/SMAP_E_OPL/TOOLSUBS.F90
> +        CALL h5close_f(hdferr)
Wrap in `#if (defined USE_HDF5)` preprocessor check.

2022-06-16 18:13 UTC, bmcandr commented on ldt/SMAP_E_OPL/TOOLSUBS.F90
> +        CALL h5close_f(hdferr)
Wrap in `#if (defined USE_HDF5)` preprocessor check.

2022-07-22 17:55 UTC, emkemp commented
Hi @yhkwon81 

I dusted off this pull request, and there are issues that need to be addressed.

* Documentation needs to be added for new ldt.config entries.
* Parts of the code need to be wrapped in #if (defined USE_HDF5) and #endif, as HDF5 is not linked by default.

In addition, I cannot replicate the results for the VIIRS CDF nor the CDFS CDF.  In both cases LDT fails to read the GVF files, despite my ldt.config files looking very much like your samples.  I have not determined the cause yet.

Until these changes are made, the pull request will remained marked as Not Ready.

2022-07-22 18:27 UTC, yhkwon81 commented
Thanks for reminding me these. I will resolve the issues.

From: Eric Kemp ***@***.***>
Reply-To: NASA-LIS/LISF ***@***.***>
Date: Friday, July 22, 2022 at 1:55 PM
To: NASA-LIS/LISF ***@***.***>
Cc: "Kwon, Yonghwan (GSFC-617.0)[UNIVERSITY OF MARYLAND]" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [NASA-LIS/LISF] New features in LDT for GVF CDF generation and SMAP_E_OPL retrievals (PR #1110)


Hi @yhkwon81<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fyhkwon81&data=05%7C01%7Cyonghwan.kwon%40nasa.gov%7Ceaf8b510679c46e62b0a08da6c0b55e5%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637941093204992865%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lx%2F8i%2F%2FzmTOsxxjDbrLRa44jCZXMOYDraj%2BtDinYw1E%3D&reserved=0>

I dusted off this pull request, and there are issues that need to be addressed.

  *   Documentation needs to be added for new ldt.config entries.
  *   Parts of the code need to be wrapped in #if (defined USE_HDF5) and #endif, as HDF5 is not linked by default.

In addition, I cannot replicate the results for the VIIRS CDF nor the CDFS CDF. In both cases LDT fails to read the GVF files, despite my ldt.config files looking very much like your samples. I have not determined the cause yet.

Until these changes are made, the pull request will remained marked as Not Ready.

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNASA-LIS%2FLISF%2Fpull%2F1110%23issuecomment-1192810152&data=05%7C01%7Cyonghwan.kwon%40nasa.gov%7Ceaf8b510679c46e62b0a08da6c0b55e5%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637941093204992865%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XSWY1hWWhYHnYPhbxQDtHskc5pe3FyinWztk9vMui0E%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMAPSH23THQPXTQZ3P7UEBDVVLOADANCNFSM5YDR5MYQ&data=05%7C01%7Cyonghwan.kwon%40nasa.gov%7Ceaf8b510679c46e62b0a08da6c0b55e5%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637941093204992865%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xwhjONZ82JYHNE0wTIc4Dt60wc2DGOpQM0v8PUCyQKU%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-07-22 18:39 UTC, emkemp commented
Thanks @yhkwon81 

Update on my end:  I figured out why the VIIRS and CDFS files weren't being read in (silly user error).  I've started rerunning for comparison with your test case.

Also, I notice that for the SMAP case, 'diff' indicates my ARFS_SM_V_01798_D_20150603T122325_R17000_001.dat is not the same as yours.  Is it possible to plot these files and look at the differences?

2022-07-22 19:04 UTC, yhkwon81 commented
Thanks for the update. Please let me know if you encounter any further issues.
Could you direct me to your SMAP case directory?

From: Eric Kemp ***@***.***>
Reply-To: NASA-LIS/LISF ***@***.***>
Date: Friday, July 22, 2022 at 2:40 PM
To: NASA-LIS/LISF ***@***.***>
Cc: "Kwon, Yonghwan (GSFC-617.0)[UNIVERSITY OF MARYLAND]" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [NASA-LIS/LISF] New features in LDT for GVF CDF generation and SMAP_E_OPL retrievals (PR #1110)


Thanks @yhkwon81<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fyhkwon81&data=05%7C01%7Cyonghwan.kwon%40nasa.gov%7C2314416cb6f44cb75f4208da6c119a53%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637941120107915713%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9r%2FAspYnxE%2BDlUpsPn0it7lPlpqPyF0%2FwwA6syu36L8%3D&reserved=0>

Update on my end: I figured out why the VIIRS and CDFS files weren't being read in (silly user error). I've started rerunning for comparison with your test case.

Also, I notice that for the SMAP case, 'diff' indicates my ARFS_SM_V_01798_D_20150603T122325_R17000_001.dat is not the same as yours. Is it possible to plot these files and look at the differences?

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNASA-LIS%2FLISF%2Fpull%2F1110%23issuecomment-1192842172&data=05%7C01%7Cyonghwan.kwon%40nasa.gov%7C2314416cb6f44cb75f4208da6c119a53%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637941120107915713%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RyjngT9jFt4aKLvC5LxAtltG%2BFr1mD81MutZkrqUgxA%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMAPSH32XZRJP2MIXAIKZVTVVLTILANCNFSM5YDR5MYQ&data=05%7C01%7Cyonghwan.kwon%40nasa.gov%7C2314416cb6f44cb75f4208da6c119a53%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637941120107915713%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kCIbThzgxNl8ocmSrZVUXl3FdPy024kgtvL4kgjjcxg%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-07-22 19:06 UTC, emkemp commented
Sure, it's /discover/nobackup/emkemp/pr/1110/work_sm

Read permissions *should* be set for your access.

2022-07-23 14:07 UTC, yhkwon81 commented
Thanks. I think that my results were generated before fixing some bugs in LDT. I re-generated the SMAP_E_OPL soil moisture using the bug-fixed LDT, and “diff” shows that yours and mine are the same. My new results are in the same directory (/discover/nobackup/projects/usaf_lis/ykwon/SMAP_E_OPL/testcases/TEST_01_usecase/SM_retrieval).


From: Eric Kemp ***@***.***>
Reply-To: NASA-LIS/LISF ***@***.***>
Date: Friday, July 22, 2022 at 3:06 PM
To: NASA-LIS/LISF ***@***.***>
Cc: "Kwon, Yonghwan (GSFC-617.0)[UNIVERSITY OF MARYLAND]" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [NASA-LIS/LISF] New features in LDT for GVF CDF generation and SMAP_E_OPL retrievals (PR #1110)


Sure, it's /discover/nobackup/emkemp/pr/1110/work_sm

Read permissions should be set for your access.

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNASA-LIS%2FLISF%2Fpull%2F1110%23issuecomment-1192859330&data=05%7C01%7Cyonghwan.kwon%40nasa.gov%7C98e27fb33d604c7e874608da6c1544ef%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637941135851309661%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jyTuv0sBzb3ViWIZHzAUEXTT%2BuQxvY05B3ObmfavzIQ%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMAPSHZK7YZE5KPIEGLUVG3VVLWKXANCNFSM5YDR5MYQ&data=05%7C01%7Cyonghwan.kwon%40nasa.gov%7C98e27fb33d604c7e874608da6c1544ef%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637941135851309661%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2GbbwUu%2BcJFoSiVBg1QQzK1sYNE9RkNHM4%2F%2BAS0lg08%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-07-28 21:34 UTC, emkemp commented
Hi @yhkwon81 

Can you open up read permissions to /discover/nobackup/projects/usaf_lis/ykwon/SMAP_E_OPL/testcases/TEST_01_usecase/SM_retrieval?  I'm locked out.

2022-07-29 15:19 UTC, yhkwon81 commented
I am sorry. I changed the permission. Please try again.

From: Eric Kemp ***@***.***>
Reply-To: NASA-LIS/LISF ***@***.***>
Date: Thursday, July 28, 2022 at 5:34 PM
To: NASA-LIS/LISF ***@***.***>
Cc: "Kwon, Yonghwan (GSFC-617.0)[UNIVERSITY OF MARYLAND]" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [NASA-LIS/LISF] New features in LDT for GVF CDF generation and SMAP_E_OPL retrievals (PR #1110)


Hi @yhkwon81<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fyhkwon81&data=05%7C01%7Cyonghwan.kwon%40nasa.gov%7Cfbd055c05d40473088ad08da70e0eb7d%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637946408573457548%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4iYkPCACuPEMqY7G4wAAje4zv9ff%2BA8NY6DGyU2ca%2FM%3D&reserved=0>

Can you open up read permissions to /discover/nobackup/projects/usaf_lis/ykwon/SMAP_E_OPL/testcases/TEST_01_usecase/SM_retrieval? I'm locked out.

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNASA-LIS%2FLISF%2Fpull%2F1110%23issuecomment-1198656082&data=05%7C01%7Cyonghwan.kwon%40nasa.gov%7Cfbd055c05d40473088ad08da70e0eb7d%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637946408573457548%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BDAS8o5ewRbkwD5ZiNM5gPPpUS7H%2FW8ouS%2FBzmdXDsU%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMAPSH5PBAQ6BPG6QYQTJRLVWL4FJANCNFSM5YDR5MYQ&data=05%7C01%7Cyonghwan.kwon%40nasa.gov%7Cfbd055c05d40473088ad08da70e0eb7d%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637946408573457548%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Y8trKmBrkE%2FoojC2YN5%2BzwQ%2F%2FtqzZHBDa3jMkRLMT1c%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-07-29 16:49 UTC, emkemp commented
Thanks @yhkwon81!  I confirm I get identical results for ARFS_SM_V_01798_D_20150603T122325_R17000_001.dat.

I added some HDF5 related preprocessing statements to ldt/SMAP_E_OPL/TOOLSUBS.F90.  I will commit to the branch.

2022-07-29 19:15 UTC, emkemp commented
Hi @yhkwon81 

I reproduced the netCDF output files for both the VIIRS and CDFS test cases.

You still need to add documentation for the new ldt.config options.  Once that is done, I will coordinate with @jvgeiger on where/how to store your test cases before accepting the pull request.

2022-08-16 19:49 UTC, emkemp commented
Hi @yhkwon81 

Thanks for updating the documentation.  At this point I believe the pull request itself is ready.  I want to confer with @jvgeiger on handling your test cases before we proceed.  Fingers crossed, this pull request will be accepted by the end of the week.

2022-09-27 21:20 UTC, merged