Updates the LIS NUOPC cap - Rebased onto Oct 2020 revision of LIS
NASA-LIS/LISF pull request #618
Opened 2020-10-29 17:02 UTC by danrosen25

This update includes changes to the LIS NUOPC cap developed during LIS-WRFHydro coupling.
- NoahMP.3.6 Coupling
- NoahMP.4.0.1 Coupling
- Ensemble Coupling and Ensemble Mean Coupling
- Coupling bug fixes
- ASO DA bug fixes
- LIS_isDAinstanceValid allocation fix
- Code cleanup

LISHydro Application: https://github.com/NESII/LISHydro

The solution to Coupled NoahMP.4.0.1 has changed.

### Reviewed solution changes
Baseline: https://github.com/NESII/LISF/tree/feature/NUOPC_outdated/lis
 - [x] Coupled LIS-WRFHydro NoahMP.3.6 OL
 - [x] Coupled LIS-WRFHydro NoahMP.4.0.1 OL Coldstart
 - [x] Coupled LIS-WRFHydro NoahMP.4.0.1 DA Ensemble 20 members

### Recommended testing
 - [ ] Offline (LIS exe) - Compared to master branch (LIS exe)
 - [ ] Standalone (NUOPC exe) NoahMP4.0.1 OL - Compared to master branch (LIS exe)
 - [ ] Standalone (NUOPC exe) NoahMP4.0.1 DA - Compared to master branch (LIS exe)

2020-11-12 19:34 UTC, bmcandr requested changes
Hi @danrosen25. I've just about completed the recommended testing and everything looks to be in working order. I have a few minor requests:

* The routing mod bug related to `LIS_isDAinstanceValid` was fixed in #604 so the changes introduced to lines 247-255 of `LIS_routingMod.F90` are no longer necessary.
* In `lis/arch/configure.agrmet`:
    * Line 4: value should be 1 to select GRIBAPI (as in the other configure files)
* In `lis/core/LIS_DAobservationsMod.F90`:
     * `gridtype` input variable never used in new version (but still within old code within `#if 0` block)
    * Lines 598-602: remove commented code unless potentially needed later. (Appears to have been replaced by 603-604...)
* In `lis/core/LIS_mpDecomp.c`:
    * Clean up commented code if not needed (i.e., lines 107-109, 150-157, 211-218, 233)
* In `lis/runmodes/nuopc_cpl_mode/LIS_NUOPC_DataCopy.F90`:
    * Indent nested loops for readability (`grep "row=1"` to find)
* In `lis/runmodes/nuopc_cpl_mode/LIS_NUOPC_Gluecode.F90`:
    * Clean up commented code if not needed (i.e., line 877, 890-897, etc.)
* In `lis/runmodes/nuopc_cpl_mode/LIS_NUOPC_Cap.F90`:
    * Clean up commented calls to `NUOPC_CompGet` if not needed
* In `lis/surfacemodels/land/noahmp.3.6/cpl_wrf_noesmf/noahMP36_setwrfexport.F90`:
    * Clean up commented code if not needed.
* In `lis/surfacemodels/land/noahmp.4.0.1/cpl_wrf_noesmf/noahMP401_setwrfexport.F90`:
    * Clean up commented out code if not needed.
* In `lis/surfacemodels/land/noahmp.4.0.1/phys/module_sf_noahmplsm_401.F90`:
    * Only addition is commented out code. Remove if not needed.

@jvgeiger, do you see anything that should also be addressed before merging? There are some large changes to core files (e.g., `LIS_DAobservationsMod.F90`) that could use a once over from experienced eyes. Also, should the NUOPC cap be mentioned in docs anywhere?

2020-11-12 19:36 UTC, jvgeiger commented
I will take a look.  Thanks.

2020-12-23 20:32 UTC, jvgeiger commented
Hello. 

I finished my first review of the code.  Here are the files that I want to review a second time:

- [ ] Config.pl
To understand the new ESMF-related additions, the new lib_flags and lib_paths variables, and to test compiling on other systems.
- [ ] LIS_DAobservationsMod.F90
To understand why this now performs domain decomposition and why it is has copies of the decompose_nx_ny and decompose_npes routines.
- [ ] LIS_mpDecomp.c
- [ ] LIS_domainMod.F90
- [ ] LIS_ESMF_Extensions.F90
Should LIS write plotting scripts in NCL and Ferret?  Can LIS write/log required data in a language-agnostic manner and can scripting  be managed outside LIS?
- [ ] LIS_NUOPC_Cap.F90
To understand the services being set.
- [ ] LIS_NUOPC_Gluecode.F90
To understand the Init and Run routines.

The @NASA-LIS/lsm team should review these files:

- [ ] module_sf_noah33lsm.F90
- [ ] module_sf_noahmp36lsm.F90
- [ ] noahmp_driver_36.F90
- [ ] noahmp_driver_401.F90
- [ ] module_sf_noahmplsm_401.F90

2021-01-19 21:18 UTC, danrosen25 commented
I've made most of the updates @bmcandr recommended. @TimLahmers @sujayvkumar please review the changes request for
- lis/core/LIS_DAobservationsMod.F90
- lis/surfacemodels/land/noahmp.4.0.1/phys/module_sf_noahmplsm_401.F90

@jvgeiger, When do you want to review this PR together?

2021-01-19 21:34 UTC, danrosen25 commented
I will follow up on my own comment. @bmcandr @jvgeiger I also plan to merge this branch with the LISF/master branch and test it. I think it will help if I resolve any merge conflicts. Do you agree?

2021-01-19 22:02 UTC, bmcandr commented
@danrosen25, I just cleanly merged master into this branch so there are no merge conflicts between these branches at present. That said, it's probably a good idea to bring this branch up to date with master for testing purposes given there have been changes to master since this PR was opened.

2021-01-19 22:05 UTC, dmocko commented
The @NASA-LIS/lsm also needs to finish taking a look at the 5 files that @jvgeiger requested.  We will get on this as soon as possible.

2021-01-20 00:55 UTC, TimLahmers commented on lis/surfacemodels/land/noahmp.4.0.1/phys/module_sf_noahmplsm_401.F90
> +!         IF (QSNOW > 0.) then
@danrosen25 These lines were commented out, as they were causing an error. They can be removed.

2021-01-20 01:01 UTC, TimLahmers commented on lis/core/LIS_DAobservationsMod.F90
> +             !call LIS_quilt_obs_domain(n, k, map_proj, gnc, gnr,&
These commented out lines call the original version of LIS_quilt_obs_domain. @sujayvkumar made this change as a temporary fix to add support for Lambert Conformal DA. I recommend making one of these a new subroutine and adding an if statement to call this or the original subroutine v. the new subroutine that supports Lambert DA. Should consult with @jvgeiger and @bmcandr before doing this, as it seems like a major change.

2021-01-20 01:03 UTC, TimLahmers commented on lis/core/LIS_DAobservationsMod.F90
> +! !INTERFACE:
@danrosen25 This is the new LIS_quilt_obs_domain subroutine for Lambert DA. Old version above is commented out. @sujayvkumar @bmcandr @jvgeiger Finding a way to incorporate both subroutines should be decided by LIS team before we proceed.

2021-01-20 01:05 UTC, TimLahmers commented on lis/core/LIS_DAobservationsMod.F90
> +    character(len=*), intent(in)  :: gridtype
@danrosen25 I see gridtype isn't used. This variable is used in the old subroutine, so I am hesitant to remove (see comments to LIS team above).

2021-01-21 21:30 UTC, bmcandr commented on lis/core/LIS_DAobservationsMod.F90
> +! !INTERFACE:
Thanks for the explanation, Tim. Since the Lambert DA version of the `LIS_quilt_obs_domain` routine takes different arguments than the "old" version I'm inclined to agree with your suggestion above that these routines be distinguished somehow (e.g., call this one `LIS_quilt_obs_domain_lambert` or something). That said, maybe Sujay, Jim, or Dan have a better idea.

2021-01-21 21:34 UTC, bmcandr commented
@TimLahmers, can you also comment on Jim's item asking "why [*LIS_DAobservationsMod.F90*] now performs domain decomposition and why it is has copies of the `decompose_nx_ny` and `decompose_npes` routines" from *LIS_domainMod.F90*? The `cut`, `inner_factors`, and `count` routines also appear to be copied over from *LIS_domainMod.F90*. See lines 2486-3218 in [this commit](https://github.com/NASA-LIS/LISF/commit/cd2ceed536bc68dd2c6db717a8c7b540c2f3620c#diff-9dddd438703ed52c6d937ebf7a9bcb6034bb8b7788f250d03bd646ba2c1bf262R2491) vs. [line 2816](https://github.com/NASA-LIS/LISF/blob/0f38019b981f277f54e62b819028f0527a2e6090/lis/core/LIS_domainMod.F90#L2816) in *LIS_domainMod.F90*.

I diffed these lines and they *appear* identical aside from some whitespace differences.

2021-01-21 21:56 UTC, dmocko commented on lis/surfacemodels/land/noahmp.4.0.1/phys/module_sf_noahmplsm_401.F90
> +!         IF (QSNOW > 0.) then
@TimLahmers Do you mean the commenting out can be removed, or the entire lines should be removed?

What error occurs?  I am reluctant to change Noah-MP code in the "phys" sub-directories, unless there is a very compelling reason.

2021-01-21 23:01 UTC, TimLahmers commented on lis/surfacemodels/land/noahmp.4.0.1/phys/module_sf_noahmplsm_401.F90
> +!         IF (QSNOW > 0.) then
@dmocko The commented lines are redundant to other code and can be removed. They were left from a previous version of the code and replaced by lines 2970-2973, which permit calibration. Uncommenting those lines will result in model errors.

2021-01-21 23:03 UTC, TimLahmers commented on lis/core/LIS_DAobservationsMod.F90
> +! !INTERFACE:
@bmcandr That is a good point. Today @sujayvkumar and I discussed it on a conference call, and Sujay would prefer to modify the LIS_quilt_obs_domain_lambert subroutine to support any domain type. I am open to both approaches.

2021-01-22 17:32 UTC, danrosen25 commented on lis/surfacemodels/land/noahmp.4.0.1/phys/module_sf_noahmplsm_401.F90
> +!         IF (QSNOW > 0.) then
This commented out code has been removed in commit f8beb5f37a36b05e61245e0af47c687b5e97c98d

2021-01-22 22:47 UTC, dmocko commented
> The @NASA-LIS/lsm team should review these files:
> 
> * [ ]  module_sf_noah33lsm.F90
> * [ ]  module_sf_noahmp36lsm.F90
> * [ ]  noahmp_driver_36.F90
> * [ ]  noahmp_driver_401.F90
> * [ ]  module_sf_noahmplsm_401.F90

The @NASA-LIS/lsm team has reviewed the above files as requested.
Here are our findings:

module_sf_noahmplsm_401.F90:
  Now there are no changes, as commented-out code was removed.

module_sf_noah33lsm.F90:
  We are fine with these changes.

module_sf_noahmp36lsm.F90:
  We recommend removing line #9 instead of commenting it out.

noahmp_driver_36.F90:
  We recommend removing line #9 instead of commenting it out,
  but we are fine with the rest of the changes.

noahmp_driver_401.F90:
  We recommend removing line #13 instead of commenting it out,
  but we are fine with the rest of the changes.

Although not requested by @jvgeiger , changes to the other LSM-
associated files are also fine with the lsm team.

It's not on the testing list, but we recommend testing these codes
before merging against the master branch, using these experiments:
  Offline Open Loop Noah-3.3
  Offline Open Loop Noah-MP-3.6
  Offline Open Loop Noah-MP-4.0.1

Thanks - the @NASA-LIS/lsm team.

2021-02-10 22:11 UTC, danrosen25 commented
Hi @jvgeiger @bmcandr @dmocko 
I [removed](https://github.com/NASA-LIS/LISF/pull/618/commits/227bf66bef8a7232f5fe0a2203e4e39ee4e6a8aa) commented out WRF_HYDRO preprocessor macro.

@TimLahmers @sujayvkumar,
Can you look into these issues 

**lis/core/LIS_DAobservationsMod.F90**
- [ ] gridtype input variable never used in new version (but still within old code within #if 0 block)
- [ ] Lines [598-602](https://github.com/NASA-LIS/LISF/blob/227bf66bef8a7232f5fe0a2203e4e39ee4e6a8aa/lis/core/LIS_DAobservationsMod.F90#L598 ): remove commented code unless potentially needed later. (Appears to have been replaced by 603-604...)

2021-02-10 22:27 UTC, TimLahmers commented
@danrosen25 For the first issue, I do not see the grid type variable anywhere else, so I think it can probably be removed. We should confirm with @sujayvkumar though.

For second issue, lines 598-602 can be probably be removed. Sujay, please correct me if this is wrong.

2021-02-16 01:32 UTC, danrosen25 commented
Hi @bmcandr @jvgeiger @dmocko 
Tim, Sujay, and I resolved remaining issues in LIS_DAobservationsMod.F90 and the conflicts in dataassim/obs MCD15A2H_LAI. Please review at your earliest convenience and merge this as soon as possible. Regarding files in the runmodes/nuopc_cpl_mode folder. All of these files are built on top of the LIS library and they are not included in the default build.

2021-02-22 19:08 UTC, jvgeiger commented
Here is my follow up review:

* Subroutine lis_quilt_obs_domain (in LIS_DAobservationsMod.F90)
  * Remove gridtype — not used
  * Remove map_proj — not used
  * Remove "use easeV2_utils" — not used
  * Fix "call LIS_quilt_obs_domain" accordingly

* Subroutine LIS_mapTileSpaceToObsSpace (in LIS_DAobservationsMod.F90)
  * Remove this routine.
  * It has been replaced with LIS_surfaceModel_DAmapTileSpaceToObsSpace, LIS_lsm_DAmapTileSpaceToObsSpace, LIS_routing_DAmapTileSpaceToObsSpace.
  * Nothing calls this routine — jules5x_map_snopdep and jules5x_map_usafsi erroneously call this routine.  Jim will fix these to files to call LIS_lsm_DAmapTileSpaceToObsSpace.

* LIS_NUOPC_Gluecode.F90 contains init, run, and finalize routines for NUOPC coupled running mode.

* LIS_NUOPC_Cap.F90 wraps LIS within a NUOPC cap.
  * Documentation contains a section on dependencies.  This is out of date.

* LIS_ESMF_Extensions.F90 contains support code.
  * Many of these routines seem to support writing Ferret and NCL plotting scripts for four defined domains:
    * GLOBAL -90.0, 90.0, -180.0, 180.0
    * CONUS 18.0, 49.0, 235.0, 298.0
    * IRENE 10.0, 60.0, 240.0, 320.0
    * FRONTRANGE 38.5, 41.0, -107.0, -103.5
  * This seems like project specific support rather than generic NUOPC support.
  * Which routines are needed for generic NUOPC support?

* runmodes/nuopc_cpl_mode/analysis
  * These seem like project specific plotting scripts.
  * I suggest either removing them or placing them in lis/utils under an appropriately named sub-directory.

* Fix copyright notices on the files in runmodes/nuopc_cpl_mode.

2021-03-02 19:18 UTC, bmcandr commented
- [ ] In `LIS_DAobservationsMod.F90` remove:
  - [ ] `subroutine decompose_nx_ny`
  - [ ] `subroutine decompose_npes`
  - [ ] `subroutine cut`
  - [ ] `subroutine inner_factors`
  - [ ] `function count_mask`

These routines already exist in _LIS_domainMod.F90_ so they can be referenced in this file with a `use LIS_domainMod`.

2021-03-03 23:45 UTC, danrosen25 commented
@bmcandr @jvgeiger 
`LIS_mapTileSpaceToObsSpace` is called in a few places and they need to be removed before I can remove this subroutine from `LIS_DAobservationsMod.F90`. Is the code to remove these calls straight forward? Should we change this code after the merge?
- [ ] dataassim/algorithm/ekf/ekf_Mod.F90:          call LIS_mapTileSpaceToObsSpace(n, k, LIS_rc%lsm_index, &
- [ ] dataassim/algorithm/ekf/ekf_Mod.F90:             call LIS_mapTileSpaceToObsSpace(n, k, LIS_rc%lsm_index, t, st_id, en_id)
- [ ] dataassim/algorithm/ensrf/ensrf_Mod.F90:          call LIS_mapTileSpaceToObsSpace(n, k, LIS_rc%lsm_index, &
- [ ] dataassim/algorithm/ensrf/ensrf_Mod.F90:             call LIS_mapTileSpaceToObsSpace(n, k, LIS_rc%lsm_index, t, st_id, en_id)
- [ ] surfacemodels/land/jules.5.x/da_snodep/jules5x_map_snodep.F90:     call LIS_mapTileSpaceToObsSpace(n, k, LIS_rc%lsm_index, &
- [ ] surfacemodels/land/jules.5.x/da_usafsi/jules5x_map_usafsi.F90:     call LIS_mapTileSpaceToObsSpace(n, k, LIS_rc%lsm_index, &

2021-03-04 00:11 UTC, danrosen25 commented
decompose_nx_ny and decompose_npes aren't public subroutines in LIS_domainMod.F90. I plan to add the following.
```
  public :: decompose_nx_ny          !decomposes domain based on proc layout
  public :: decompose_npes           !decomposes domain based on proc elements
```

2021-03-04 16:09 UTC, bmcandr commented
Hi @danrosen25,

Re: `LIS_mapTileSpaceToObsSpace` -- @jvgeiger recently fixed the calls in the _jules.5.x_ files in #715. It looks like a straightforward change for the other two files (change the routine name, drop the `LIS_rc%lsm_index` argument, and add `use LIS_lsmMod` up top).

Re: `decompose_n*` -- making those public looks ok to me.

Thanks for tackling these changes!

2021-03-05 16:03 UTC, bmcandr commented
Thanks for making these changes @danrosen25. The cleanup in _arch/Config.pl_ broke the if-block at line 985 as it left an orphan `else{`. I made a fix on my local copy of the repo, but don't have permission to push to the NESII fork. [See fix here.](https://github.com/NESII/LISF/compare/feature/NUOPC...bmcandr:feature/NUOPC-bmc?expand=1)

2021-03-05 21:36 UTC, bmcandr commented
Using my local fix, I was able to complete some initial testing:

 - [ ] Offline (LIS exe) - Compared to master branch (LIS exe)
 - [x] Standalone (NUOPC exe) NoahMP4.0.1 OL - Compared to master branch (LIS exe)
 - [x] Standalone (NUOPC exe) NoahMP4.0.1 DA - Compared to master branch (LIS exe)

I'm currently running the changes through the internal testsuite to tick off box one above.

----

Also: a PR merged today caused a conflict in `lis/make/default.cfg` that will have to be fixed before this can be merged. I'd make the fix if not for those pesky permissions...!

2021-03-05 21:58 UTC, danrosen25 commented
@bmcandr Thanks for the fix and I took care of the conflict.

2021-03-08 14:55 UTC, bmcandr approved these changes

2021-03-08 15:01 UTC, bmcandr commented
The changes look good now and passed [testing](https://github.com/NASA-LIS/LISF/pull/618#issuecomment-791725435) with the Intel19 compiler. I'll go ahead and merge now.

2021-03-08 15:01 UTC, merged

2021-03-08 15:19 UTC, TimLahmers commented
Thanks @bmcandr

I am glad to put this complex PR behind us!

@danrosen25 @sujayvkumar Next we need to update LIS/WRF-Hydro to point to the NASA/LISF repo and move LIS/WRF-Hydro to NASA. How do we proceed with that?