Add new WRF forcing reader in LIS and elev in LDT
NASA-LIS/LISF pull request #818
Opened 2021-06-24 18:19 UTC by karsenau

A new WRF-based forcing reader has been implemented into
 LIS that supports higher-res, CONUS-wide WRF datasets.

 Also along with the new forcing reader, WRF-based elevation
 terrain map support is also incorporated in LDT and can be
 used with the new WRF reader in LIS.

 New options are highlighted in the "configs" documents.

This applies to feature issue #811 and completes that ticket.

### Testcase

Test cases for this reader are found here:
/discover/nobackup/karsenau/LISF_PR/WRF_ForcReader

In the "LIS_Test" subdirectory, all files are provided, except the parameters and forcing are provided via symbolic line ("input") which points to the top-level LIS data disk.  All paths should be final and the person evaluating this pull-request and test-case, should be able to copy the directory "as-is" to their test directory. Also, sample "target" output and files are provided in the same directory of the test-case run with the new forcing reader (found in the local dir: NoahMP401_WRFforc_NoLR_target).

Finally, the WRF-forcing terrain file also has a reader to support it on the LDT side and can be switched on in LIS by selecting "lapse-rate" in your lis.config file. The LDT testcase for this set up is found here:

/discover/nobackup/karsenau/LISF_PR/WRF_ForcReader/LDT_Test

For any further information or have any questions, please contact @karsenau.

2021-06-30 20:43 UTC, bmcandr requested changes
Hi @karsenau,

The code looks good overall, but I have a few minor cleanup requests.

I'm also seeing some slight differences between my output and the target for the LIS *LRcorr* test. Can you take a peek at the output and see if this looks good to you? See the output in `*LRcorr_test` in `/discover/nobackup/projects/lis/PR_TESTCASES/818/testing/WRF_ForcReader/LIS_Test`.

2021-06-30 20:43 UTC, bmcandr commented on lis/metforcing/WRFoutv2/0Intro_WRFoutv2.txt
> +!-------------------------END NOTICE -- DO NOT EDIT-----------------------
Update copyright to 2020 version:

```
!-----------------------BEGIN NOTICE -- DO NOT EDIT-----------------------
! NASA Goddard Space Flight Center
! Land Information System Framework (LISF)
! Version 7.3
!
! Copyright (c) 2020 United States Government as represented by the
! Administrator of the National Aeronautics and Space Administration.
! All Rights Reserved.
!-------------------------END NOTICE -- DO NOT EDIT-----------------------
```

2021-06-30 20:43 UTC, bmcandr commented on lis/metforcing/WRFoutv2/WRFoutv2_forcingMod.F90
> +    !pcp     <--> LIS_forc%metdata1(8,:)
Remove if not needed.

2021-06-30 20:43 UTC, bmcandr commented on lis/metforcing/WRFoutv2/read_WRFoutv2.F90
> +!       print *, trim(WRFoutv2_fv(v))//" ... datain(1,2): ",datain(1,2)    ! t=2 ==> T2=295.283
Remove if not needed.

2021-06-30 20:43 UTC, bmcandr commented on lis/metforcing/WRFoutv2/read_WRFoutv2.F90
> +!              if(v.eq.1 .and. f(c).ne.-9999.0) write(LIS_logunit,*) c,f(c)
Remove if not needed.

2021-06-30 20:43 UTC, bmcandr commented on lis/metforcing/WRFoutv2/read_WRFoutv2.F90
> +!        tg = -9999.0
Remove if not needed.

2021-06-30 20:43 UTC, bmcandr commented on lis/metforcing/WRFoutv2/readconfig_WRFoutv2.F90
> +  enddo
Should `WRF nest id:` be read from the config? It is listed in `lis.config.adoc` as an option.

2021-06-30 20:53 UTC, bmcandr commented
Not sure why the first comment shows up twice... I tried out the inline review feature and must have done something wrong!

2021-07-01 20:56 UTC, karsenau commented
Hi @bmcandr:

Thank you so much for the thorough review of the code and testcase results.

I just checked your testcase outputs for the "lapse-rate" correction case against the "target" output (that I generated), and I didn't see much difference, checked for date/timestamps: 2004101903, 2004102009

Was there a particular date/time that you saw differences?

Thanks!

2021-07-01 21:07 UTC, karsenau reviewed
Updates made, per @bmcandr's review and suggestions.

2021-07-07 16:19 UTC, bmcandr requested changes
> Hi @bmcandr:
> 
> Thank you so much for the thorough review of the code and testcase results.
> 
> I just checked your testcase outputs for the "lapse-rate" correction case against the "target" output (that I generated), and I didn't see much difference, checked for date/timestamps: 2004101903, 2004102009
> 
> Was there a particular date/time that you saw differences?
> 
> Thanks!

Hi @karsenau,

I'm seeing some small differences between the target and test outputs for several dates when I compare them with `nccmp -dsf`. They are very small so I just wanted to make sure they are OK with you. If you'd like to see what I'm talking about, `cd` to my testing directory and run:

```shell
for TARGET in $(find NoahMP401_WRFforc_LRcorr_target -name "LIS_HIST*.nc"); do TEST=${TARGET/target/test}; echo $TEST; nccmp -dsf $TARGET $TEST; done
```

----

I have a few more revisions to request on the files added for the Alaska domain. Also, is there a testcase for the AK domain reader?

2021-07-08 13:37 UTC, bmcandr commented
After speaking with @karsenau, the requested changes to the Alaska domain reader will be deferred until a later pull request.

Otherwise, the code looks good and I was able to reproduce the results with both the Intel19 and GNU9 compilers. Merging.

2021-07-08 13:38 UTC, bmcandr approved these changes

2021-07-08 13:38 UTC, merged

2021-07-23 13:02 UTC, karsenau commented
The new WRF Alaska (AK) reader in LIS and its elevation file reader in LDT are now ready, along with test cases for LDT and LIS (with and without topographic corrections).

The test case files can be found here:

LDT:  /discover/nobackup/karsenau/LISF_PR/WRF_AKReader/LDT_Test
LIS:  /discover/nobackup/karsenau/LISF_PR/WRF_AKReader/LIS_Test

This PR addresses feature issue #812 .