Feature/ld tensrst upd
NASA-LIS/LISF pull request #853
Opened 2021-07-22 15:48 UTC by sujayvkumar

### Modifies the ensemble restart transformation capabilities in LDT

The ensemble restart generation has been modified to allow random sampling options when going from an restart file with certain number of ensembles to another restart file with a different number of ensemble members. 

### Testcase
Upscaling case:   /discover/nobackup/karsenau/LISF_PR/LDT_Ensrst_Upscale
 
Downscaling case:  /discover/nobackup/karsenau/LISF_PR/LDT_Ensrst_Downscale

2021-07-22 15:53 UTC, karsenau commented
Yes, please find our test cases here:

Upscaling case:   /discover/nobackup/karsenau/LISF_PR/LDT_Ensrst_Upscale
 
Downscaling case:  /discover/nobackup/karsenau/LISF_PR/LDT_Ensrst_Downscale

2021-07-27 15:48 UTC, bmcandr requested changes

2021-07-27 15:48 UTC, bmcandr commented on ldt/core/LDT_ran2_gasdev.F90
> +       stop
Change:
* `write (*,*)` to `write (LDT_logunit, *)`
* `stop` to `LDT_endrun()`

@sujayvkumar @karsenau, I'm happy to make these changes if you approve. These fixes should also be made to `lis/core/LIS_ran2_gasdev.F90` (perhaps in a subsequent PR).

2021-07-27 15:53 UTC, bmcandr commented
I have finished reviewing and testing. I made two minor changes:

* Updated the copyright notice in `LDT_ran2_gasdev.F90`
* Added `Ensemble restart generation sampling strategy` to the LDT user guide. **Please review this entry.**

I have also requested a change to `LDT_ran2_gasdev.F90` indicated in the comment above.

Testing produced identical output with both Intel 19 and GNU9 compilers. Once the changes are reviewed and resolved this PR will be ready to merge.

2021-07-27 16:05 UTC, karsenau commented on ldt/core/LDT_ran2_gasdev.F90
> +       stop
Hi @bmcandr, 

Yes, thank you -- that will be great. You can go ahead and make these changes.

2021-07-27 16:09 UTC, karsenau approved these changes

2021-07-27 16:09 UTC, karsenau commented on ldt/core/LDT_ran2_gasdev.F90
> +       stop
Just make sure to include the module 'use' call to 'LDT_logMod' for LDT_logunit

2021-07-27 17:24 UTC, bmcandr commented on ldt/core/LDT_ran2_gasdev.F90
> +       stop
Done!

2021-07-27 17:24 UTC, merged

2021-08-31 17:53 UTC, karsenau commented
New updates made for the HyMAP2 Routing LDT-based ensemble restart support -- "random sampling"

Commit made to master branch (feature branch: feature/hymap_ensrst from karsenau) and to be pulled into the 557WW LIS7.4 support branch (@jvgeiger )