Feature/obs sim ldt
NASA-LIS/LISF pull request #867
Opened 2021-07-30 22:11 UTC by rkim3

### Description
Implemented a new observation simulator in LDT. This simulator can handle the use of external orbital masks to be applied to the observations created for OSSEs. Currently, AMSR2, TSMM, Sentinel-1A, and MODIS are available instrumental options.

### Testcase
The test case files can be found here:
/discover/nobackup/rkim3/TestCase/ObsSim

2021-08-02 18:50 UTC, bmcandr commented
Hi @rkim3, I made a few commits to resolve the conflicts and fix a compile time error. Here is what I changed:

* Removed the file `ldt/core/LDT_ran2_gasdev.F90`. This file was recently added to LDT in #853.
* Merged the master branch into your feature branch. This replaced the file removed above and allowed me to resolve the conflict in `ldt/make/Filepath`
* Added type statements to `ldt/obsSim/OSSEmask/AMSR2/AMSR2OSSEmask_Mod.F90` for the variables `cornerlat1`, `cornerlat2`, `cornerlon1`, and `cornerlon2` at lines 81-82. Without this fix, compiling would result in an error message: `This name does not have a type, and must have an explicit type`.

I still need to review the remaining files, but have to hop over to another task at the moment. I'll try to revisit this today if I have time.

2021-08-03 20:59 UTC, bmcandr requested changes
Hi @rkim3,

I have completed my initial review. Before continuing, I recommend updating your local branch with my changes by running `git pull`.

Then, I kindly request that you address the specific changes requested in my review comments and:

1. Update the LDT config documentation (`ldt/configs/ldt.config.adoc`) to include the new config entries added here (e.g., lines 91-92 in `ldt/obsSim/NatureRun/LISout/LISoutNatureRun_Mod.F90`)
2. Update the copyright notice at the top of newly added files (see review comment below).

___

@emkemp, can you review the `*FTable.c` files added here? They look similar to existing `*FTable.c` files in `ldt/core/`, but I'd like more experienced eyes to check them over.

2021-08-03 20:59 UTC, bmcandr commented on ldt/obsSim/NatureRun/LISout/readLISoutNatureRun.F90
> +   character(len=*),   optional :: map_proj
These optional arguments are not used in this routine and cause the GNU compiler to throw an error:

```sh
Error: Explicit interface required for ‘create_lisout_ossemask_filename’ at (1): optional argument
make: *** [readLISoutOSSEmask.o] Error 1
make: *** Waiting for unfinished jobs....
obsSim/NatureRun/LISout/readLISoutNatureRun.F90:47:39:

            47 |   call create_lisout_naturerun_filename(n, &
                |                                       1
Error: Explicit interface required for ‘create_lisout_naturerun_filename’ at (1): optional argument
make: *** [readLISoutNatureRun.o] Error 1
```

To fix, remove these optional arguments from the routine definition (line 131) and the routine call (lines 54-55).

2021-08-03 20:59 UTC, bmcandr commented on ldt/obsSim/OSSEmask/LISout/readLISoutOSSEmask.F90
> +   character(len=*),   optional :: map_proj
Same issue as in `ldt/obsSim/NatureRun/LISout/readLISoutNatureRun.F90`. Remove these unused optional arguments to make the GNU compiler happy.

2021-08-04 13:26 UTC, emkemp commented
I just pushed updates to the new C code.  I didn't notice any bugs -- the changes are just subjective improvements to indentation and spacing.

2021-08-04 13:30 UTC, emkemp commented on ldt/core/LDT_obsSimMod.F90
> +    call system('mkdir -p '//trim(dname))
Instead of call system('mkdir -p '//trim(dname)), use:

integer :: rc
external :: LDT_create_subdirs
...
rc = LDT_create_subdirs(len_trim(dname), trim(dname))
if (rc .ne. 0) then
  write(LDT_logunit,*)'[ERR] Cannot create directory ', trim(dname)
  call LDT_endrun()
end if

2021-08-04 13:31 UTC, emkemp commented on ldt/core/LDT_obsSimMod.F90
> +    call system('mkdir -p '//trim(dname))
We're still in a holding pattern on going through all the LISF code and replacing the system calls.  I'll raise this issue at the weekly Air Force meeting today, since that project is where this problem was first encountered.

2021-08-04 13:34 UTC, emkemp commented
As this code is improved, I recommend test compiling with Intel with strict checks (-3).  I just ran it now, and the compilation fails.

2021-08-04 20:18 UTC, bmcandr commented
> As this code is improved, I recommend test compiling with Intel with strict checks (-3). I just ran it now, and the compilation fails.

@emkemp, do you recall what errors you were seeing? I can compile with Intel + strict checks just fine. Any chance you were compiling in parallel? I made that mistake at first and compile failed in some of the `*_genmod.f90` files the compiler generates.

2021-08-04 20:40 UTC, emkemp commented
Hi @bmcandr 

I just compiled LDT again with -3 using the lisf_7_intel_19_1_3_304 module.  Fresh clone from github, and no parallel build.  I get this error:

../obsSim/NatureRun/LISout/readLISoutNatureRun.F90(54): error #8055: The procedure has a dummy argument that has the ALLOCATABLE, ASYNCHRONOUS, OPTIONAL, POINTER, TARGET, VALUE or VOLATILE attribute. Required explicit interface is missing from original source.   [RUN_DD]
       LISoutNatureRunData%run_dd, &       
---------------------------^
../obsSim/NatureRun/LISout/readLISoutNatureRun.F90(55): error #8055: The procedure has a dummy argument that has the ALLOCATABLE, ASYNCHRONOUS, OPTIONAL, POINTER, TARGET, VALUE or VOLATILE attribute. Required explicit interface is missing from original source.   [MAP_PROJ]
       LISoutNatureRunData%map_proj)
---------------------------^
compilation aborted for ../obsSim/NatureRun/LISout/readLISoutNatureRun.F90 (code 1)
Makefile:108: recipe for target 'readLISoutNatureRun.o' failed
make: *** [readLISoutNatureRun.o] Error 1

2021-08-04 20:50 UTC, emkemp commented
...and I concur this is a syntax error.  Subroutine create_lisout_naturerun_filename has two optional arguments, but the subroutine itself is not in a module and does not have an interface block associated with it.  That violates ISO Fortran.

2021-08-04 21:56 UTC, rkim3 commented
Hi @bmcandr and @emkemp, 

Thanks for reviewing this. I just pushed updates including all the changes you suggested.

2021-08-04 23:38 UTC, bmcandr commented
@emkemp, sorry--I had removed those unused optional arguments locally for testing which allowed compilation to succeed with strict checks.

What changes would you recommend making to comply with ISO Fortran? Placing these subroutines within a module? Still learning over here :)

2021-08-05 02:23 UTC, bmcandr commented
Thanks @rkim3! The copyright notices had extra spaces in them and the unused optional arguments were still present in one of the files so I rolled back a few of your commits and made the fixes.

I also made some edits to the documentation to add missing config entries, note acceptable values, group the entries, and fix some formatting. Please take a look [here](https://github.com/rkim3/LISF/blob/feature/obsSimLDT/ldt/configs/ldt.config.adoc#observation-simulator) to see if it looks ok!

Since I rolled back a few of your commits, I recommend using `git pull --force` to update your local branch.

----

At this point, testing has produced identical results with both Intel 19 and GNU9 compilers. 👍

2021-08-05 13:09 UTC, emkemp commented
Hi @bmcandr:

I was going to recommend moving the problem subroutines into the module, so the compiler automatically creates interfaces to check for optional arguments.  However, @rkim3 changed the subroutines to remove the optional arguments altogether, and ifort is now happy.

2021-08-05 13:45 UTC, rkim3 commented
Hi @bmcandr ,

Thanks for making these fixes. The documentation looks great!

2021-08-05 13:52 UTC, bmcandr approved these changes
The changes look good, the compilers are happy, and I am able to produce identical results. I will go ahead and merge.

2021-08-05 13:52 UTC, merged