Fix for global domain HYMAP parameter setup where a boundary box of m…
NASA-LIS/LISF pull request #887
Opened 2021-08-24 19:14 UTC by hkato1

### Description

HYMAP flow direction parameters (i.e. HYMAP_flow_direction_x and HYMAP_flow_direction_y) created in LDT for global domain have missing values in adjacent grid cells along 180W longitude, resulting in missing values for the HYMAP routing output fields simulated in LIS.  This issue applies only for global domain and appears over the northeastern edge of Russia.  The flow directions are designed to have outlet cells outlining the simulation domain to prevent flow in/out of the domain boundary, however, the boundary should not be applied in global domain simulations.  Two steps are required to fix this issue: 1) check the  HYMAP input parameters prepared by Augusto @agetiran --some of the parameters have missing values along 180W as well, however, the new input parameters based on MERIT data are corrected.  2) Add the fix made in ldt/params/HYMAP/HYMAP_parmsMod.F90

Resolves #886 

### Testcase

path:/discover/nobackup/hkato/GLDAS/noahmp025run
ldt config file: ldt.config_noahmp401_gldas20_025d_hymap2
initial output with the problem: noahmp401_hymap2_gldas20_025d_gap_lisf.nc 
fixed output: noahmp401_hymap2new_gldas20_025d.nc
GrADS control files to view outputs : param_gldas2.0_noahmp401_gap.xdf and paramnew_gldas2.0_noahmp401.xdf

2021-09-09 17:58 UTC, bmcandr commented
Hi @hkato1,

Can you please open permissions on `MODEL_OUTPUT_LIST.TBL.gldas2p5.grib2` when you have a moment? I am unable to copy this file over for testing. Thanks!

2021-09-09 18:05 UTC, hkato1 commented
Hi Brendan,
Done.  Sorry about that!
Hiroko
________________________________
From: Brendan McAndrew ***@***.***>
Sent: Thursday, September 9, 2021 1:58 PM
To: NASA-LIS/LISF ***@***.***>
Cc: Beaudoing, Hiroko Kato (GSFC-617.0)[UNIVERSITY OF MARYLAND] ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [NASA-LIS/LISF] Fix for global domain HYMAP parameter setup where a boundary box of m… (#887)


Hi @hkato1<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhkato1&data=04%7C01%7CHiroko.Kato-1%40nasa.gov%7C65223dffab60445bf86d08d973bb74a1%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637668071225987387%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bZ9SKJ%2BM%2Bw05MVg%2F7Wuu4s1kGlb%2FWRB%2FVCdgssDE3dY%3D&reserved=0>,

Can you please open permissions on MODEL_OUTPUT_LIST.TBL.gldas2p5.grib2 when you have a moment? I am unable to copy this file over for testing. Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNASA-LIS%2FLISF%2Fpull%2F887%23issuecomment-916316527&data=04%7C01%7CHiroko.Kato-1%40nasa.gov%7C65223dffab60445bf86d08d973bb74a1%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637668071225987387%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ea5rFuzJOzZekW3Qmxtffr8TZCLjMnOePNg9wxG68GE%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAB372U5C4NQOMCAONJWTNTTUBDYU3ANCNFSM5CXPOHBQ&data=04%7C01%7CHiroko.Kato-1%40nasa.gov%7C65223dffab60445bf86d08d973bb74a1%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637668071225997336%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=N%2FkWRUS2DPArfAcQbynn1aMmI2gTt6UTZaWEftyvGRc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CHiroko.Kato-1%40nasa.gov%7C65223dffab60445bf86d08d973bb74a1%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637668071225997336%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OQnOfQ%2B9gNPwdKhT5uu10fpt7oEa9JYrbSiFUyWEKD4%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CHiroko.Kato-1%40nasa.gov%7C65223dffab60445bf86d08d973bb74a1%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637668071226007298%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8nB55WuoPSsYg5pgoCPXX%2F%2BJpaT6Jvv4TINGyUUfbxA%3D&reserved=0>.

2021-09-09 18:07 UTC, bmcandr commented
No worries!

2021-09-09 18:09 UTC, bmcandr commented
Actually, looks like permissions still aren't open. I'm only seeing rwx for the owner group.

2021-09-09 18:13 UTC, hkato1 commented
OK, this time in the correct directory.  Sorry!
________________________________
From: Brendan McAndrew ***@***.***>
Sent: Thursday, September 9, 2021 2:09 PM
To: NASA-LIS/LISF ***@***.***>
Cc: Beaudoing, Hiroko Kato (GSFC-617.0)[UNIVERSITY OF MARYLAND] ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [NASA-LIS/LISF] Fix for global domain HYMAP parameter setup where a boundary box of m… (#887)


Actually, looks like permissions still aren't open. I'm only seeing rwx for the owner group.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNASA-LIS%2FLISF%2Fpull%2F887%23issuecomment-916323859&data=04%7C01%7CHiroko.Kato-1%40nasa.gov%7C128b4eac38f946549e8008d973bcf14e%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637668077609059252%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wCaBH4S2C3IquWcsPqKNwE6%2FNFyqxTy0yvJ%2B5L2P3x8%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAB372U2NDCTQYY3GXA7V6DTUBDZ43ANCNFSM5CXPOHBQ&data=04%7C01%7CHiroko.Kato-1%40nasa.gov%7C128b4eac38f946549e8008d973bcf14e%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637668077609069207%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=k2IWcEWQoQPFw3iEYn2ejHkuqbSvZRm9mmGJHjQfq9k%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CHiroko.Kato-1%40nasa.gov%7C128b4eac38f946549e8008d973bcf14e%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637668077609069207%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tfiqe%2FTZAJ1BAWMQ4R9iilidi3VKaEBWwqaeLYQSyAs%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CHiroko.Kato-1%40nasa.gov%7C128b4eac38f946549e8008d973bcf14e%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637668077609069207%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JdyN0dDvyvz3ceoqn7CWpCoWERyxjYMPevf3eqQVHRQ%3D&reserved=0>.

2021-09-09 18:15 UTC, bmcandr commented
That did the trick! :)

2021-09-09 19:33 UTC, bmcandr requested changes

2021-09-09 19:33 UTC, bmcandr commented on ldt/params/HYMAP/HYMAP_parmsMod.F90
> +     print*,'HYMAP parameter global'
Replace call to `print*` with call to `write(LDT_logunit,*)`. Also, should this log message start with the `[INFO]` tag?

2021-09-09 19:36 UTC, hkato1 commented
Yes, that sounds good.  Thanks!
________________________________
From: Brendan McAndrew ***@***.***>
Sent: Thursday, September 9, 2021 3:33 PM
To: NASA-LIS/LISF ***@***.***>
Cc: Beaudoing, Hiroko Kato (GSFC-617.0)[UNIVERSITY OF MARYLAND] ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [NASA-LIS/LISF] Fix for global domain HYMAP parameter setup where a boundary box of m… (#887)


@bmcandr requested changes on this pull request.

________________________________

In ldt/params/HYMAP/HYMAP_parmsMod.F90<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNASA-LIS%2FLISF%2Fpull%2F887%23discussion_r705637863&data=04%7C01%7CHiroko.Kato-1%40nasa.gov%7C06613ccd221844c2b1b508d973c8c0da%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637668128335544678%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vUKNCY860Y4pfuK6bxNIpqQyo3hN6ZBYdMbsrsoh8rg%3D&reserved=0>:

> @@ -760,25 +761,39 @@ subroutine adjust_nextxy(nx,ny,imis,i2nextx,i2nexty,i2mask,zgx,zgy,zpx,zpy,xres,
     where(i2nextx>0)i2nextx=i2nextx-idx
     where(i2nexty>0)i2nexty=i2nexty-idy

-    i2nexty(1,:)=imis
-    i2nexty(nx,:)=imis
-    i2nexty(:,1)=imis
-    i2nexty(:,ny)=imis
+!Hiroko: do not insert boundary if global domain
+!        this fix only works on single processor run
+    if ( idx.eq.0 .and. idy.eq.0 ) then
+     print*,'HYMAP parameter global'


Replace call to print* with call to write(LDT_logunit,*). Also, should this log message start with the [INFO] tag?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNASA-LIS%2FLISF%2Fpull%2F887%23pullrequestreview-750745464&data=04%7C01%7CHiroko.Kato-1%40nasa.gov%7C06613ccd221844c2b1b508d973c8c0da%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637668128335554632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xEel8J%2Bs8m7VVTbX%2BYkP4ZQjnAffgZWawyYJqp1fAqY%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAB372U4Y55IAQHFSDN76AKDUBEDZZANCNFSM5CXPOHBQ&data=04%7C01%7CHiroko.Kato-1%40nasa.gov%7C06613ccd221844c2b1b508d973c8c0da%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637668128335554632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NymeXAJmJLdMH1av2dHyMUp9c6DFepwMixlKxoM%2Bl%2Fw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CHiroko.Kato-1%40nasa.gov%7C06613ccd221844c2b1b508d973c8c0da%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637668128335554632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tq2kHLxq0GABp2LHDvdzlazofTBMbo6z%2BJz6bNQW7C4%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CHiroko.Kato-1%40nasa.gov%7C06613ccd221844c2b1b508d973c8c0da%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637668128335564593%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qvAE6%2FAUR2z3awtnWjv2npMr4J57Wov%2FFApKDdtBOtQ%3D&reserved=0>.

2021-09-10 11:49 UTC, bmcandr approved these changes

2021-09-10 11:50 UTC, bmcandr commented
I successfully compiled and tested these changes with both Intel 19 and GNU 9 compilers. Merging.

2021-09-10 11:50 UTC, merged

2021-09-10 16:28 UTC, hkato1 commented
Great!  Thank you so much!
________________________________
From: Brendan McAndrew ***@***.***>
Sent: Friday, September 10, 2021 7:50 AM
To: NASA-LIS/LISF ***@***.***>
Cc: Beaudoing, Hiroko Kato (GSFC-617.0)[UNIVERSITY OF MARYLAND] ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [NASA-LIS/LISF] Fix for global domain HYMAP parameter setup where a boundary box of m… (#887)


Merged #887<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNASA-LIS%2FLISF%2Fpull%2F887&data=04%7C01%7CHiroko.Kato-1%40nasa.gov%7C7d9e933ed2534d6da42b08d974512f06%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637668714298833077%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fdf8Ja2HZXdkcrgjVm8Ql53kP6Fki1aMbGIPS6eIV48%3D&reserved=0> into support/lisf-public-7.3.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNASA-LIS%2FLISF%2Fpull%2F887%23event-5284029442&data=04%7C01%7CHiroko.Kato-1%40nasa.gov%7C7d9e933ed2534d6da42b08d974512f06%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637668714298833077%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1Qh41gePQ6RjKtL8c1N0xkb2qI%2FK%2Fn%2FVG8kVXAWzSFQ%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAB372UZJ3TT7EQD5SG3X2ZLUBHWIBANCNFSM5CXPOHBQ&data=04%7C01%7CHiroko.Kato-1%40nasa.gov%7C7d9e933ed2534d6da42b08d974512f06%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637668714298843020%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=R4LPL3Hbioo4%2BXNuXlsg%2FHXOwtn%2BM%2BoQPaNVHzdmb20%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CHiroko.Kato-1%40nasa.gov%7C7d9e933ed2534d6da42b08d974512f06%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637668714298843020%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YdX0ib%2Fqf312lKV%2BTsansfXUB%2B0%2BWWkASmmt3p7VgB0%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CHiroko.Kato-1%40nasa.gov%7C7d9e933ed2534d6da42b08d974512f06%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637668714298843020%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NE9M%2BqKfR474qmfGfxW8RRdCTljNYfnvGHZw5vmts%2Fo%3D&reserved=0>.