Feature/plumber2
NASA-LIS/LISF pull request #943
Opened 2021-11-23 21:54 UTC by TimLahmers

### Description

Resolves issue #942 by including PLUMBER2 reader. PLUMBER2 reader is included in the /lis/metforcing/plumber2/ directory, and configuration files have been updated to support the reader when LIS is compiled.

### Testcase

This reader has been tested in the directory: /discover/nobackup/projects/nu-wrf/members/tlahmers/SUNY_Albany_MAP2020/RUN/LIS_PLUMBER2_OL_test19October2021

Note that each PLUMBER2 forcing file contains the full time series for one site, making the forcing slightly different compared to other forcing types. The lis.config file in the sample directory includes forcing information for the test case. 

Site specific lis.config settings with the new reader include:
LIS domain and parameter data file:    ./lis_input.nldas.noahMP.plumberkm.nc
PLUMBER2 forcing file: ./productionINPUT/AU-Cow_2010-2015_OzFlux_Met.nc
PLUMBER2 Station ID: AU-Cow
PLUMBER2 Time Delta: 1800
Noah-MP.4.0.1 model timestep: 30mn #SITE SPECIFIC
Surface model output interval:          "30mn" #"1800ss" #SITE SPECIFIC "1da"

2021-11-24 16:30 UTC, bmcandr commented
Hi @TimLahmers, can you please recursively open permissions on your testcase directory when you get a moment? There are some files I'm unable to copy in the INPUT and output directories. Thanks!

2021-11-24 19:41 UTC, TimLahmers commented
All of the files in the INPUT directory have read access now, and the only OUTPUT directory needed for verification is OL_OUTPUTkm_1123/. Everything in that directory is now also accessible. Will it be necessary to re-test the code after the commit from earlier this afternoon?

2021-11-24 19:59 UTC, bmcandr commented
Thanks @TimLahmers. I haven't run a test yet. I'll let you know if my results differ from yours.

2021-11-29 20:06 UTC, bmcandr commented
Hi @TimLahmers,

I was able to run your testcase successfully with an executable compiled with default optimization (2), but strict optimization has highlighted a few issues we need to resolve before we can merge this code into master.

Using an executable compiled with strict optimization (-2), my run stops at line 42 of `readcrd_plumber2.F90` when attempting to set `plumber2_struc(n)%stnid` to the value read from the lis.config file with the following error:

```forrtl: severe (408): fort: (8): Attempt to fetch from allocatable variable STNID when it is not allocated```

Looking at the code, `plumber2_struc(n)%stnid` has not been allocated when line 42 is executed. The array is allocated on line 322 in `plumber2_forcingMod.F90`, after the `readcrd_plumber2()` routine is called on line 140.

I made a quick patch by allocating `plumber2_struc(n)%stnid` to size 1 before the call to `readcrd_plumber2()` (based this on the code at lines 318 and 322 in `plumber2_forcingMod.F90`). The "fixed" executable proceeds past the error above, but halts again shortly thereafter with the following error and traceback:

```bash
forrtl: severe (408): fort: (2): Subscript #3 of the array MODELOUTPUT has value 2 which is greater than the upper bound of 1

Image              PC                Routine            Line        Source
LIS.i19.strict.fi  0000000008E209DF  Unknown               Unknown  Unknown
LIS.i19.strict.fi  000000000142E4C1  lis_histdatamod_m        6474  LIS_histDataMod.F90
LIS.i19.strict.fi  000000000142A9A7  lis_histdatamod_m        6371  LIS_histDataMod.F90
LIS.i19.strict.fi  00000000014272CA  lis_histdatamod_m        6148  LIS_histDataMod.F90
LIS.i19.strict.fi  00000000020AA633  noahmp401_main_           990  NoahMP401_main.F90
LIS.i19.strict.fi  00000000016F3E8A  lsmrun_                   476  LIS_lsm_FTable.c
LIS.i19.strict.fi  00000000016ACF74  lis_lsmmod_mp_lis         619  LIS_lsmMod.F90
LIS.i19.strict.fi  00000000019A2390  lis_surfacemodelm         248  LIS_surfaceModelMod.F90
LIS.i19.strict.fi  00000000083C5C65  retrospective_run         198  retrospective_runMod.F90
LIS.i19.strict.fi  0000000001915330  lisrun_                   202  LIS_runmode_FTable.c
LIS.i19.strict.fi  0000000004DDB27A  MAIN__                     70  lisdrv.F90
LIS.i19.strict.fi  0000000000414292  Unknown               Unknown  Unknown
libc-2.22.so       00002AAAB4B4F725  __libc_start_main     Unknown  Unknown
LIS.i19.strict.fi  00000000004141A9  Unknown               Unknown  Unknown
```

This appears unrelated to your changes, however.

Summary of the fault:
* `NOAHMP401_struct(n)%nsnow` is set to 3 layers [here](https://github.com/NASA-LIS/LISF/blob/master/lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_readcrd.F90#L103) and `dataEntry%modelOutput` has a shape of (i, j, 1)
* The 3 layers of `NOAHMP401_struct(n)%nsnow` are looped over [here](https://github.com/NASA-LIS/LISF/blob/master/lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_main.F90#L989-L992) to call `LIS_diagnoseOutputVar` which then calls `diagnoseDataEntry`.
* The index out of bounds error occurs in the second iteration when `diagnoseDataEntry` is called with `vlevel=2` and an attempt is made to set `dataEntry%modelOutput(1,t,vlevel)` to a new value [on line 6474-6475](https://github.com/NASA-LIS/LISF/blob/0f1ce0a983300dc262bbbc7831b5e20c38f6786b/lis/core/LIS_histDataMod.F90#L6473-L6474).

@jvgeiger, do you have an idea of why this might be happening? I tried to run it down in TotalView, but it has been stalling on me.

2021-11-29 20:27 UTC, dmocko commented
Hi @bmcandr - this may be happening because of the MODEL_OUTPUT_LIST.TBL file for the testcase:

#short_name select? units signconv timeavg? min/max? std? vert.levels grib_id grib_scalefactor longname
SnowTProf:    1  K       -    1 0 0 1 239 100      # Temperature of the snow pack (K)

The "1" just before the "239" is the number of vertical levels.  I believe that LIS is dimensioning this output variable based on this "1" in that column.  Please trying to change this number to "3" for the number of vertical output levels for this variable:

SnowTProf:    1  K       -    1 0 0 3 239 100      # Temperature of the snow pack (K)

2021-11-29 20:28 UTC, bmcandr commented
Thanks @dmocko! I suspected it might have something to do with config/variable settings so I'll give that a try.

2021-11-29 20:39 UTC, bmcandr commented
That did the trick. The testcase is now running without issue.

2021-11-29 20:56 UTC, bmcandr requested changes
Hi @TimLahmers,

I have finished my review. See the inline comments I've made for details. I'm happy to make the code changes I requested if you approve. Please let me know.

2021-11-29 20:56 UTC, bmcandr commented on lis/metforcing/plumber2/plumber2_forcingMod.F90
> +          allocate(plumber2_struc(n)%stnid(plumber2_struc(n)%nstns))
Move lines 318 and 322 into a `do n=1, LIS_rc%nnest` loop after line 139, but before the call to `readcrd_plumber2()`. This will fix the unallocated array error I described in my comment on the PR thread.

2021-11-29 20:56 UTC, bmcandr commented on lis/metforcing/plumber2/timeinterp_plumber2.F90
> +        !            write(LIS_logunit,*) plumber2_struc(n)%metdata1(2,index1),plumber2_struc(n)%metdata2(2,index1)
Are the commented out `write(LIS_logunit,*)` calls in this file leftover from debugging? If so, can they be removed?

2021-11-29 22:44 UTC, TimLahmers commented
Hi Brendan,

Thanks for the update. These changes look good, but I want to also pass them through the SUNY Albany developers to verify that they do not affect anything in the code.

I will follow up with you based on their response.

Thanks,
Tim Lahmers

From: Brendan McAndrew ***@***.***>
Reply-To: NASA-LIS/LISF ***@***.***>
Date: Monday, November 29, 2021 at 3:56 PM
To: NASA-LIS/LISF ***@***.***>
Cc: "Lahmers, Timothy (GSFC-617.0)[UNIVERSITY OF MARYLAND]" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [NASA-LIS/LISF] Feature/plumber2 (PR #943)


@bmcandr requested changes on this pull request.

Hi @TimLahmers<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTimLahmers&data=04%7C01%7Ctimothy.lahmers%40nasa.gov%7C5c4ec824802b47ad320408d9b37ab490%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637738161865479597%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OY7nWCUFRfu6wX3w6Ps0Qn2SSAB0CRaue61iGSexx4g%3D&reserved=0>,

I have finished my review. See the inline comments I've made for details. I'm happy to make the code changes I requested if you approve. Please let me know.

________________________________

In lis/plugins/LIS_pluginIndices.F90<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNASA-LIS%2FLISF%2Fpull%2F943%23discussion_r755534795&data=04%7C01%7Ctimothy.lahmers%40nasa.gov%7C5c4ec824802b47ad320408d9b37ab490%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637738161865489553%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SWKXBREAqMU6UWu5pehKj3L9TvKJjCsHZr1Pgi%2B%2FLGg%3D&reserved=0>:

> +!CRF/MCB 20210921-------------------------------------------------------------

+!        Add PLUMBER2 met forcing capability

+character*50, public,  parameter :: LIS_plumber2Id        = "PLUMBER2"

+!------------------------------------------------------------------------

Let's move this down after line 178 so it's with it's friends in the metforcing section.

________________________________

In lis/metforcing/plumber2/read_plumber2.F90<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNASA-LIS%2FLISF%2Fpull%2F943%23discussion_r755535778&data=04%7C01%7Ctimothy.lahmers%40nasa.gov%7C5c4ec824802b47ad320408d9b37ab490%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637738161865489553%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=D%2Fm%2FPM4zEbDoy9oXNC5zTA057IHEroEYf6sgdF2g994%3D&reserved=0>:

> +!-----------------------BEGIN NOTICE -- DO NOT EDIT-----------------------

+! NASA Goddard Space Flight Center Land Information System (LIS) v7.1

+!

+! Copyright (c) 2015 United States Government as represented by the

+! Administrator of the National Aeronautics and Space Administration.

+! All Rights Reserved.

+!-------------------------END NOTICE -- DO NOT EDIT-----------------------

Need to update the copyright notices. (I can handle this, Tim. Just making a note for myself).

________________________________

In lis/metforcing/plumber2/plumber2_forcingMod.F90<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNASA-LIS%2FLISF%2Fpull%2F943%23discussion_r755535856&data=04%7C01%7Ctimothy.lahmers%40nasa.gov%7C5c4ec824802b47ad320408d9b37ab490%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637738161865499509%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PHTEy5tB7ZLYvz4%2BPk0uoHfI1TunCydOUSNj8O0mhdU%3D&reserved=0>:

> +  PRIVATE

+!-----------------------------------------------------------------------------

+! !PUBLIC MEMBER FUNCTIONS:

+!-----------------------------------------------------------------------------

+  public :: init_plumber2 !defines the native resolution of

+                                       !the input data

+!-----------------------------------------------------------------------------

+! !PUBLIC TYPES:

+!-----------------------------------------------------------------------------

+  public :: plumber2_struc

+!EOP

+

+  type, public :: plumber2_type_dec

+

+     real                     :: ts

+     character*256            :: plumber2file

Need to update this to use LIS_CONST_PATH_LEN once that PR is merged.

________________________________

In lis/metforcing/plumber2/readcrd_plumber2.F90<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNASA-LIS%2FLISF%2Fpull%2F943%23discussion_r756230631&data=04%7C01%7Ctimothy.lahmers%40nasa.gov%7C5c4ec824802b47ad320408d9b37ab490%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637738161865499509%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=icBs29%2BCo%2FvbzWmKhQQjLBc6AvYpY12WAztJBLB9Mo8%3D&reserved=0>:

> +      call ESMF_ConfigFindLabel(LIS_config,                            &

+                                "PLUMBER2 forcing file:",rc=rc)

+      do n = 1,LIS_rc%nnest

+         call ESMF_ConfigGetAttribute(LIS_config,                      &

+                            plumber2_struc(n)%plumber2file,rc=rc)

+      enddo

+

+      call ESMF_ConfigFindLabel(LIS_config,                           &

+                                "PLUMBER2 Station ID:",rc=rc)

+      do n = 1,LIS_rc%nnest

+         call ESMF_ConfigGetAttribute(LIS_config,                      &

+                            plumber2_struc(n)%stnid,rc=rc)

+      enddo

+

+      call ESMF_ConfigFindLabel(LIS_config,                            &

+                                "PLUMBER2 Time Delta:",rc=rc)

Add PLUMBER2 to lis/configs/lis.config.adoc:

  *   Met forcing sources: table
  *   Add config entries to new PLUMBER2 section under "Forcings" header

________________________________

In lis/metforcing/plumber2/plumber2_forcingMod.F90<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNASA-LIS%2FLISF%2Fpull%2F943%23discussion_r758726271&data=04%7C01%7Ctimothy.lahmers%40nasa.gov%7C5c4ec824802b47ad320408d9b37ab490%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637738161865509467%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FVYLrZ3JfuFgOHabp64ovp9Qj2aCL890K3OBMIQuvfM%3D&reserved=0>:

> +          plumber2_struc(n)%nstns = 1

+

+          plumber2_struc(n)%read_index = 0

+

+          allocate(plumber2_struc(n)%stnid(plumber2_struc(n)%nstns))

Move lines 318 and 322 into a do n=1, LIS_rc%nnest loop after line 139, but before the call to readcrd_plumber2(). This will fix the unallocated array error I described in my comment on the PR thread.

________________________________

In lis/metforcing/plumber2/timeinterp_plumber2.F90<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNASA-LIS%2FLISF%2Fpull%2F943%23discussion_r758728437&data=04%7C01%7Ctimothy.lahmers%40nasa.gov%7C5c4ec824802b47ad320408d9b37ab490%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637738161865509467%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=EfeIA0Uiz6Q%2FEwIM5n4SoZdB6NjY4U8QylvfmHp2qbg%3D&reserved=0>:

> +

+  do t = 1,LIS_rc%ntiles(n)

+     index1 = LIS_domain(n)%tile(t)%index

+

+     !! -- pcp (1)

+     ! Precip rate is not interpolated, but carried forward

+     if (plumber2_struc(n)%metdata1(1,t).ne.plumber2_struc(n)%undef) then

+        pcp(t) = plumber2_struc(n)%metdata1(1,index1)

+     endif

+

+     !! -- psurf (2)

+     if ((plumber2_struc(n)%metdata1(2,t).ne.plumber2_struc(n)%undef).and.        &

+          (plumber2_struc(n)%metdata2(2,t).ne.plumber2_struc(n)%undef)) then

+        psurf(t) = wt1 * plumber2_struc(n)%metdata1(2,index1) +                      &

+             wt2 * plumber2_struc(n)%metdata2(2,index1)

+        !            write(LIS_logunit,*) plumber2_struc(n)%metdata1(2,index1),plumber2_struc(n)%metdata2(2,index1 [...]

2021-12-03 19:21 UTC, TimLahmers commented
@bmcandr I sent these changes to the SUNY Albany Team earlier in the week, and they are ok if we proceed. Is there anything I need to do to approve the changes?

2021-12-03 19:25 UTC, bmcandr commented
Thanks for the update @TimLahmers. I have made the changes I described to a feature branch that I will merge into your branch. I will test again before merging and let you know if I encounter any issues.

I will also update the documentation. Can you please provide a description of the `PLUMBER2 Time Delta:` entry for the docs?

2021-12-03 20:09 UTC, TimLahmers commented
@bmcandr Thanks for the update. Please use the description "PLUMBER2 site-specific forcing time step (seconds)" for the "PLUMBER2 Time Delta:" variable in the docs. Please let me know if you need any other information or testing to complete the PR.

2021-12-06 15:02 UTC, bmcandr approved these changes

2021-12-06 21:32 UTC, bmcandr commented
These changes compile without issue on Intel 2021.04 and GNU 11.2 compilers. Testing produced identical results to target.

Packaged testcase inputs and outputs are available at: /discover/nobackup/projects/lis/PR_TESTCASES/packaged/ready_for_tcs/plumber2forcingtest

Merging.

2021-12-06 21:33 UTC, merged