Adds the support for the GDDP reader
NASA-LIS/LISF pull request #990
Opened 2022-02-20 16:17 UTC by sujayvkumar

Adds the support for the NEX GDDP climate data as forcing. The plugin
temporally disaggregates the daily GDDP data to subdaily resolution.

The code also updates includes updates to the parameter reading routines
so that in a multiprocessor mode, each process directly reads the subsetted
data slice. The older version of the code read the global data and subsetted it.

Resolves #989

### Description

Replace this text with a concise description of *what* was changed and *why*.

### Testcase

2022-02-20 16:17 UTC, sujayvkumar commented
A testcase is at : /discover/nobackup/projects/lis/svkumar/CASI2/GSFC_run

2022-02-22 17:57 UTC, bmcandr commented
Hi @sujayvkumar,

The logs in my test run are filled with warnings about the SW radiation exceeding a max value, but these messages are not in your logs. Example:

```
[INFO] reading..
 ./input/MET_FORCING/NEX-GDDP-CMIP6//TaiESM1/historical/r1i1p1f1//tas/tas_day_Ta
 iESM1_historical_r1i1p1f1_gn_1957.nc
[INFO] LIS cycle time: 06/01/1957 02:00:00
[INFO] LIS cycle time: 06/01/1957 03:00:00
[INFO] LIS cycle time: 06/01/1957 04:00:00
[INFO] LIS cycle time: 06/01/1957 05:00:00
[INFO] LIS cycle time: 06/01/1957 06:00:00
[INFO] LIS cycle time: 06/01/1957 07:00:00
[INFO] LIS cycle time: 06/01/1957 08:00:00
[INFO] LIS cycle time: 06/01/1957 09:00:00
[INFO] LIS cycle time: 06/01/1957 10:00:00
 [WARN] sw radiation too high!!
 [WARN] it is           0           3   1384.366
 [WARN] data1=   1384.366
 [WARN] data2=   1384.366
 [WARN] wts=  0.0000000E+00   1.000000
 [WARN] zw1=  0.0000000E+00 zw2=   1.000000
 [WARN] swt1=  0.0000000E+00 swt2=   1.000000
 [WARN] sw radiation too high!!
 [WARN] it is           0           8   1452.208
 [WARN] data1=   1452.208
 [WARN] data2=   1452.208
 [WARN] wts=  0.0000000E+00   1.000000
 [WARN] zw1=  0.0000000E+00 zw2=   1.000000
 [WARN] swt1=  0.0000000E+00 swt2=   1.000000
...
```

These warnings continue for ~6000 lines before LIS cycles the next timestep. Aside from these messages, our logs and restart outputs are identical. Any idea what is causing this?

2022-02-22 19:24 UTC, sujayvkumar commented
@bmcandr  - I think I turned off these warning statements in my code during testing. You can ignore them and focus on the outputs.

2022-02-22 22:27 UTC, bmcandr requested changes
Hi @sujayvkumar,

Our outputs are identical, but I identified several minor changes that should be made before merging (see review comments on PR). I'm happy to make these changes if you approve.

I will also add this reader to the documentation.

2022-02-22 22:27 UTC, bmcandr commented on lis/core/LIS_fileIOMod.F90
>  ! All Rights Reserved.
Update copyright notice

2022-02-22 22:27 UTC, bmcandr commented on lis/core/LIS_fileIOMod.F90
> +   use ESMF
Remove duplicate `use ESMF` to appease Sonarqube scans (see 9100a91)

2022-02-22 22:27 UTC, bmcandr commented on lis/core/LIS_fileIOMod.F90
> +!          LIS_nse_halo_ind(n,LIS_localPet+1))
Remove commented out code like this (multiple files)

2022-02-22 22:27 UTC, bmcandr commented on lis/metforcing/gddp/get_gddp.F90
> +           stop
Write to `LIS_logunit` and call `LIS_endrun()`

2022-02-22 22:27 UTC, bmcandr commented on lis/metforcing/gddp/get_gddp.F90
> +           stop
Log to `LIS_logunit` and call `LIS_endrun()`

2022-02-22 22:27 UTC, bmcandr commented on lis/metforcing/gddp/read_gddp.F90
> +!  close(100)
Remove debugging code

2022-02-22 22:27 UTC, bmcandr commented on lis/metforcing/gddp/read_gddp.F90
> +!  stop
Remove debugging code

2022-02-22 22:27 UTC, bmcandr commented on lis/metforcing/gddp/read_gddp.F90
> +!           endif
Remove debugging code

2022-02-22 22:27 UTC, bmcandr commented on lis/metforcing/gddp/read_gddp.F90
> +!              endif
Remove debugging code

2022-02-22 22:27 UTC, bmcandr commented on lis/metforcing/gddp/read_gddp.F90
> +           print*, 'unable to fill', LIS_localPet, vid,  c,r,output_2d(c,r),found
Need more descriptive log message here (and write to `LIS_logunit`)

2022-02-22 22:27 UTC, bmcandr commented on lis/metforcing/gddp/read_gddp.F90
> +                    print*, 'negative huss ',huss_inp(c,r)
Need more descriptive log message here (and write to `LIS_logunit`)

2022-02-25 17:50 UTC, bmcandr commented
Hi @sujayvkumar,

I pushed the changes I recommended in my review. While updating the user guide, I noticed that the GDDP forcing scenario field is not validated after it is read from the lis.config file. Is `historical` the only option that is currently supported?

2022-03-01 16:32 UTC, bmcandr commented
I went ahead and added a check for the supported forcing scenario and updated the lis.config documentation.

I reproduced the target outputs with the Intel 2021 compiler. Merging

2022-03-01 16:37 UTC, bmcandr approved these changes

2022-03-01 16:37 UTC, merged

2022-03-01 16:55 UTC, sujayvkumar commented
@bmcandr  - I found some bugs and I have some updates to commit. Can you undo the merge and reopen the pull requests?

2022-03-01 16:58 UTC, bmcandr commented
@sujayvkumar sorry about that. I just reverted the merge. Pull from your remote branch to get the changes I made, make your fixes, and then you can reopen the PR when it's ready.